setwd("D:/estudos excel/acidentes PRF")

library(data.table)
library(dplyr)


df = data.table::fread(input = 'acid_2017_to_2023_portugues.csv',
                       showProgress = TRUE,
                       skip = 0,
                       nrows = -1,
                       na.strings = '',
                       encoding  = "UTF-8")

colnames(df)

df = rename(df, 
            inverse_data = data_inversa, 
            week_day = dia_semana, 
            hour = horario, 
            state =  uf,
            road_id = br,
            city = municipio,             
            cause_of_accident = causa_acidente,        
            type_of_accident = tipo_acidente,
            victims_condition = classificacao_acidente, 
            weather_timestamp = fase_dia,          
            road_direction = sentido_via,      
            wheather_condition = condicao_metereologica,
            road_type = tipo_pista,         
            road_delineation = tracado_via, 
            people = pessoas,
            deaths = mortos,
            slightly_injured = feridos_leves,         
            severely_injured = feridos_graves,         
            uninjured = ilesos, 
            ignored = ignorados,             
            total_injured = feridos,
            vehicles_involved = veiculos,
            police_station = delegacia)


df[ , c('uso_solo', 'uop', 'V1') := NULL]
sapply(df, function(x) sum(is.na(x)))

df$week_day <- factor(df$week_day,
                      levels = c('domingo', 'segunda-feira', 'terça-feira', 'quarta-feira', 'quinta-feira', 'sexta-feira', 'sábado'),
                      labels = c('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday')
)

unique(df$cause_of_accident)
df$cause_of_accident = factor(df$cause_of_accident,
                          levels = c("Defeito Mecânico no Veículo",
                                     "Velocidade Incompatível",
                                     "Condutor Dormindo",
                                     "Falta de Atenção à Condução",
                                     "Defeito na Via",
                                     "Ingestão de Álcool",
                                     "Não guardar distância de segurança", 
                                     "Pista Escorregadia",
                                     "Falta de Atenção do Pedestre",
                                     "Desobediência às normas de trânsito pelo condutor",
                                     "Fenômenos da Natureza",
                                     "Animais na Pista",
                                     "Ultrapassagem Indevida",
                                     "Mal Súbito",
                                     "Carga excessiva e/ou mal acondicionada",
                                     "Objeto estático sobre o leito carroçável",
                                     "Avarias e/ou desgaste excessivo no pneu",
                                     "Sinalização da via insuficiente ou inadequada",
                                     "Deficiência ou não Acionamento do Sistema de Iluminação/Sinalização do Veículo",
                                     "Restrição de Visibilidade",
                                     "Ingestão de Substâncias Psicoativas",
                                     "Reação tardia ou ineficiente do condutor",
                                     "Agressão Externa",
                                     "Desobediência às normas de trânsito pelo pedestre",
                                     "Ingestão de álcool e/ou substâncias psicoativas pelo pedestre",
                                     "Acumulo de areia ou detritos sobre o pavimento",
                                     "Ingestão de álcool pelo condutor",
                                     "Curva acentuada",
                                     "Desrespeitar a preferência no cruzamento",
                                     "Pedestre andava na pista",
                                     "Demais falhas mecânicas ou elétricas",
                                     "Transitar na contramão",
                                     "Pista em desnível",
                                     "Ingestão de álcool ou de substâncias psicoativas pelo pedestre",
                                     "Ausência de reação do condutor",
                                     "Chuva",
                                     "Pista esburacada",
                                     "Obras na pista",
                                     "Manobra de mudança de faixa",
                                     "Acumulo de óleo sobre o pavimento",
                                     "Condutor desrespeitou a iluminação vermelha do semáforo",
                                     "Condutor usando celular",
                                     "Acostamento em desnível",
                                     "Conversão proibida",
                                     "Acessar a via sem observar a presença dos outros veículos",
                                     "Deficiência do Sistema de Iluminação/Sinalização",
                                     "Falta de acostamento",
                                     "Mal súbito do condutor",
                                     "Acumulo de água sobre o pavimento",
                                     "Condutor deixou de manter distância do veículo da frente",
                                     "Entrada inopinada do pedestre",
                                     "Ausência de sinalização",
                                     "Transitar no acostamento",
                                     "Trafegar com motocicleta (ou similar) entre as faixas",
                                     "Demais falhas na via",
                                     "Pedestre cruzava a pista fora da faixa",
                                     "Frear bruscamente",
                                     "Afundamento ou ondulação no pavimento",
                                     "Fumaça",
                                     "Estacionar ou parar em local proibido",
                                     "Iluminação deficiente",
                                     "Acesso irregular",
                                     "Demais Fenômenos da natureza",
                                     "Problema com o freio",
                                     "Falta de elemento de contenção que evite a saída do leito carroçável",
                                     "Retorno proibido",
                                     "Obstrução na via",
                                     "Ingestão de substâncias psicoativas pelo condutor",
                                     "Desvio temporário",
                                     "Área urbana sem a presença de local apropriado para a travessia de pedestres",
                                     "Sinalização mal posicionada",
                                     "Semáforo com defeito",
                                     "Declive acentuado",
                                     "Faixas de trânsito com largura insuficiente",
                                     "Restrição de visibilidade em curvas verticais",
                                     "Neblina",
                                     "Restrição de visibilidade em curvas horizontais",
                                     "Problema na suspensão",
                                     "Participar de racha","Modificação proibida","Transitar na calçada","Faróis desregulados","Sistema de drenagem ineficiente","Redutor de velocidade em desacordo","Deixar de acionar o farol da motocicleta (ou similar)","Sinalização encoberta","Obstrução Via tentativa Assalto","Transitar no Acostamento","Suicídio (presumido)","Transtornos Mentais (exceto suicidio)"
                                     ),
                          labels = c("Mechanical loss/defect of vehicle",
                                     "Incompatible velocity",
                                     "Driver was sleeping",
                                     "Driver's lack of attention to conveyance",
                                     "Road's defect",
                                     "Alcohol consumption",
                                     'Disrespect of safe distance from the next car',
                                     "Slippery track",
                                     "Pedestrian's lack of attention",
                                     "Driver broke the laws of transit",
                                     "Natural phenomena",
                                     "Animals on the road",
                                     "The driver passed the next car improperly",
                                     "Cardiac attack",
                                     "Excessive load/cargo",
                                     "Static object on the drainage gate",
                                     "Excessive use of the car's tire",
                                     "Inadequate sinalization of the road",
                                     "Deficiency of vehicle's sinalization/ilumination system",
                                     "Visibility restriction",
                                     "Drug ingestion",
                                     "Driver's lack of reaction",
                                     "External fight",
                                     "Disobedience to laws of transit by the pedestrian",
                                     "Alcohol and/or drug ingestion by the pedestrian",
                                     "Road had lots of sand/wreckage",
                                     "Alcohol ingestion by the driver",
                                     "Curvy road",
                                     "Disrespecting the intersection",
                                     "Pedestrian was walking in the road",
                                     "Electrical or mechanical flaws",
                                     "Driver was in the opposite direction",
                                     "Unlevel track",
                                     "Alcohol and/or drug ingestion by the pedestrian",
                                     "Driver's lack of reaction",
                                     'Rain',
                                     "Roads with holes without cement",
                                     "Road works (in maintenance)",
                                     "Lane change maneuver",
                                     "Oil accumulation on the road",
                                     "Driver disrespected the red traffic light",
                                     "Driver using cellphone",
                                     "Uneven breakdown lane",
                                     'Prohibited conversion',
                                     "Acessing the road without seeing the presence of other vehicles",
                                     "Deficiency of vehicle's sinalization/ilumination system",
                                     "No breakdown lanes",
                                     "Driver had a cardiac attack",
                                     "Accumulation of water on the road",
                                     "Driver failed to keep distance from the vehicle in front",
                                     "Unexpected pedestrian entry",
                                     "Absence of sinalization",
                                     "Driving on the breakdown lane",
                                     "Traffic with a motorcycle (or similar) between lanes",
                                     "Other flaws/problems in the road",
                                     "Pedestrian was crossing the road outside of the crosswalk",
                                     "Abrupt use of the car's brake",
                                     "Sinking or ondulation in the pavement",
                                     "Smoke",
                                     "Stopping at a prohibited place",
                                     "Poor ilumination (of the road)",
                                     "Irregular access",
                                     "Natural phenomena",
                                     "Car's brake problem",
                                     "Static object on the drainage gate",
                                     "Driver changed the lane illegally",
                                     'Obstacle in the road',
                                     "Driver was using drugs",
                                     "Temporary return",
                                     "Urban area without appropriate pedestrian walking",
                                     "Bad positioning of traffic sign posts",
                                     "Traffic lights with problems",
                                     "Prominent downhill",
                                     "Pedestrian crosswalk with insufficient width",
                                     "Visibility restrictions in vertical curves",
                                     "Fog",
                                     "Visibility restrictions in horizontal curves",
                                     "Car's suspension system with problems",
                                     "engaging in drifting",
                                     "prohibited modification (of the car)",
                                     "car's on sidewalk",
                                     "unregulated headlights",
                                     "inefficiency of the drenage system",
                                     "speed reducer wasn't working correctly",
                                     "Failed to activate the motorcycle headlight (or similar)",
                                     "hidden/covered sinalization (of the road)",
                                     "robbery attempt",
                                     "driving on the breakdown lane",
                                     "suicide (presumed)",
                                     "mental disorder (except suicide)")
                          )

unique(df$type_of_accident)
table(df$type_of_accident)
df$type_of_accident <- factor(df$type_of_accident,
                              levels = c("Colisão traseira",	
                                         "Saída de leito carroçável",
                                         "Colisão frontal",
                                         "Colisão lateral",
                                         "Colisão com objeto estático",
                                         "Tombamento",
                                         "Colisão com objeto em movimento",
                                         "Derramamento de carga",
                                         "Atropelamento de Pedestre",	
                                         "Colisão transversal",
                                         "Incêndio",
                                         "Capotamento",	
                                         "Atropelamento de Animal",
                                         "Engavetamento",
                                         "Danos eventuais",
                                         "",
                                         "Queda de ocupante de veículo",	
                                         "Colisão com objeto",	
                                         "Colisão lateral mesmo sentido", 
                                         "Eventos atípicos",	
                                         "Colisão lateral sentido oposto"),
                              labels = c("Rear-end collision",
                                         "Run-off-road",
                                         "Head-on collision",
                                         "Side impact collision",
                                         "Collision with fixed object",
                                         "Overturn",
                                         "Collision with moving object",
                                         "Cargo spill",
                                         "Pedestrian collision",
                                         "Broadside collision",
                                         "Vehicle fire",
                                         "Rollover",
                                         "Animal collision",
                                         "Chain reaction crash (pile-up)",
                                         "Minor incidental damage",
                                         "Not informed",
                                         "Fall of vehicle occupant",
                                         "Collision with object",
                                         "Side collision (same direction)",
                                         "Unusual events",
                                         "Side collision (opposite direction)")
                              )

unique(df$wheather_condition)
df$wheather_condition <- factor(df$wheather_condition,
                                levels = c("Céu Claro", "\"\\\"Céu Claro\\\"\"", "Garoa/Chuvisco", "Nublado", "Sol", "Chuva", "Nevoeiro/Neblina", "Ignorado", "Vento", "Granizo", "Neve"),
                                labels = c("Clear sky", "Clear sky", "Drizzle", "Cloudy", "Sunny", "Rainy", "Fog", "Ignored", "Windy", "Hail", "Snowy")
                                )
    
unique(df$victims_condition)
df$victims_condition = factor(df$victims_condition,
                              levels = c('Com Vítimas Feridas', 'Com Vítimas Fatais', 'Sem Vítimas'),
                              labels = c('With injured victims', 'With dead victims', 'Without victims')
                              )

unique(df$weather_timestamp)
df$weather_timestamp = factor(df$weather_timestamp, 
                              levels = c("Plena Noite", "Amanhecer", "Pleno dia", "Anoitecer"),
                              labels = c("Night", "Sunrise", "Day", "Sunset")
                              )
 
unique(df$road_delineation)
df$road_delineation = factor(df$road_delineation,
                             levels = c("Reta", "Curva", "Desvio Temporário", "Não Informado", "Interseção de vias", 
                                        "Retorno Regulamentado", "Viaduto", "Rotatória", "Ponte", "Túnel"),
                             labels = c("Straight", "Curve", "Temporary Detour", "Not Reported", "Intersection", 
                                        "Authorized U-turn", "Overpass", "Roundabout", "Bridge", "Tunnel")
                             )

unique(df$road_direction)
df$road_direction = factor(df$road_direction,
                             levels = c("Decrescente", "Crescente", "Não Informado"),
                             labels = c("Decreasing", "Increasing", "Not informed")
                             )


unique(df$road_type)
df$road_type = factor(df$road_type,
                      levels = c("Simples", "Dupla", "Múltipla"),
                      labels = c("Simple", "Double", "Multiple")
                      )

df = as.data.table(df)

df <- apply(df,2,as.character)
write.table(df, file = 'accidents_2017_to_2023_english.csv', sep = ',', fileEncoding = "UTF-8", row.names = FALSE)
